services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: MemoryVault
    ports:
      - "5555:5432"
    # volumes:
    #   - ./data/postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_db
    restart: always
    ports:
      - "6479:6379"
    volumes:
      - ./data/redis_data:/data

volumes:
  postgres_data:
  redis_data: